Repository Azure-Samples/enterprise-data-sharing, pull requests merged in 2023-04, with the labels that each got.

#1 Add part of the code for final merge of Enterprise Data Sharing sample
  3-data-sharing-exploration/src/data_ingest.py
  3-data-sharing-exploration/src/data_security_basic.py
  3-data-sharing-exploration/src/helpers/config.py
  3-data-sharing-exploration/src/helpers/datasecurity/data_security_storage.py
  3-data-sharing-exploration/src/helpers/sql.py
  3-data-sharing-exploration/src/helpers/storage.py
  3-data-sharing-exploration/src/initial_setup.py
Labels: enhancement

#2 Add purview and baseline part of the code for final merge of Enterprise Data Sharing sample
  2-data-sharing-mechanism/.devcontainer/devcontainer.json
  2-data-sharing-mechanism/.gitignore
  2-data-sharing-mechanism/Readme.md
  2-data-sharing-mechanism/azure_function/.gitignore
  2-data-sharing-mechanism/azure_function/AcceptDataShareInvitations/__init__.py
  2-data-sharing-mechanism/azure_function/AcceptDataShareInvitations/configuration.py
  2-data-sharing-mechanism/azure_function/AcceptDataShareInvitations/data_share_helper.py
  2-data-sharing-mechanism/azure_function/AcceptDataShareInvitations/function.json
  2-data-sharing-mechanism/azure_function/host.json
  2-data-sharing-mechanism/azure_function/local.settings.template.json
  2-data-sharing-mechanism/azure_function/requirements.txt
  2-data-sharing-mechanism/infra/bash_setup_infra.sh
  2-data-sharing-mechanism/infra/bash_setup_sp_permissions.sh
  2-data-sharing-mechanism/infra/ps_setup_infra.ps1
  2-data-sharing-mechanism/infra/ps_setup_sp_permissions.ps1
  2-data-sharing-mechanism/media/add-data-share-permissions.png
  2-data-sharing-mechanism/media/dataset.png
  2-data-sharing-mechanism/media/invitation.png
  2-data-sharing-mechanism/media/mapping.png
  2-data-sharing-mechanism/media/schedule.png
  2-data-sharing-mechanism/media/share_created.png
  2-data-sharing-mechanism/media/snapshot.png
  2-data-sharing-mechanism/media/subscription_created.png
  2-data-sharing-mechanism/media/trigger.png
  2-data-sharing-mechanism/python/dest.py
  2-data-sharing-mechanism/python/requirements.txt
  2-data-sharing-mechanism/python/source.py
  3-data-sharing-exploration/.devcontainer/devcontainer.json
  3-data-sharing-exploration/.flake8
  3-data-sharing-exploration/.vscode/launch.json
  3-data-sharing-exploration/.vscode/settings.json
  3-data-sharing-exploration/src/.env.template
  3-data-sharing-exploration/src/__init__.py
  3-data-sharing-exploration/src/cleanup.py
  3-data-sharing-exploration/src/data_catalog.py
  3-data-sharing-exploration/src/helpers/__init__.py
  3-data-sharing-exploration/src/helpers/datacatalog/data_catalog_steps.py
  3-data-sharing-exploration/src/helpers/metadata.py
  3-data-sharing-exploration/src/helpers/purview/assets.py
  3-data-sharing-exploration/src/helpers/purview/catalog.py
  3-data-sharing-exploration/src/helpers/purview/clients.py
  3-data-sharing-exploration/src/helpers/purview/collections.py
  3-data-sharing-exploration/src/helpers/purview/datasources.py
  3-data-sharing-exploration/src/helpers/purview/scans.py
  3-data-sharing-exploration/src/requirements.txt
Labels: enhancement

#4 Review and align ReadMe files
  2-data-sharing-mechanism/Readme.md
  2-data-sharing-mechanism/images/eds-repo-sharing.drawio.svg
  3-data-sharing-exploration/README.md
Labels: documentation

#8 ydaponte/final review readme
  3-data-sharing-exploration/README.md
  README.md
Labels: documentation

#9 Correcting typo, adding links in the ReadMe
  3-data-sharing-exploration/README.md
  3-data-sharing-exploration/deploy.sh
Labels: bug, documentation
